# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 00:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0, help_text='商品数量', verbose_name='商品数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='订单的时间', verbose_name='订单的时间')),
                ('goods', models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '订单商品详情',
                'verbose_name_plural': '订单商品详情',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(default='', help_text='订单编号', max_length=100, unique=True, verbose_name='订单编号')),
                ('trade_no', models.CharField(default='', help_text='支付编号', max_length=100, unique=True, verbose_name='支付编号')),
                ('pay_status', models.CharField(choices=[('success', '成功'), ('cancel', '取消'), ('cancel', '待支付')], help_text='支付状态', max_length=15, verbose_name='支付状态')),
                ('order_mount', models.FloatField(default=0.0, help_text='支付金额', verbose_name='支付金额')),
                ('pay_time', models.DateTimeField(default=datetime.datetime.now, help_text='支付时间', verbose_name='支付时间')),
                ('address', models.CharField(default='', help_text='订单地址', max_length=200, verbose_name='订单地址')),
                ('signer_name', models.CharField(default='', help_text='签收人姓名', max_length=100, verbose_name='签收人姓名')),
                ('signer_mobile', models.CharField(default='', help_text='收货人电话', max_length=11, verbose_name='收货人电话')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0, help_text='商品数量', verbose_name='商品数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('goods', models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品')),
                ('user', models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '购物车信息',
                'verbose_name_plural': '购物车信息',
            },
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(help_text='订单', on_delete=django.db.models.deletion.CASCADE, to='trade.OrderInfo', verbose_name='订单'),
        ),
    ]
