# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20180410_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='trade_no',
            field=models.CharField(blank=True, help_text='支付编号', max_length=100, null=True, unique=True, verbose_name='支付编号'),
        ),
    ]
