# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20180413_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_sn',
            field=models.CharField(blank=True, help_text='订单编号', max_length=100, null=True, unique=True, verbose_name='订单编号'),
        ),
    ]
