# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 00:32
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='商品首页轮播图', max_length=200, null=True, upload_to='Banner/%Y/%m', verbose_name='商品首页轮播图')),
                ('index', models.IntegerField(default=0, help_text='轮播图顺序', verbose_name='轮播图顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '首页轮播图',
                'verbose_name_plural': '首页轮播图',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_sn', models.CharField(default='', help_text='商品的编号', max_length=100, verbose_name='商品的编号')),
                ('name', models.CharField(default='', help_text='商品的名称', max_length=100, verbose_name='商品的名称')),
                ('click_num', models.IntegerField(default=0, help_text='商品的点击数', verbose_name='商品的点击数')),
                ('sold_num', models.IntegerField(default=0, help_text='商品卖出数量', verbose_name='商品卖出数量')),
                ('fav_num', models.IntegerField(default=0, help_text='商品的收藏数', verbose_name='商品的收藏数')),
                ('goods_num', models.IntegerField(default=0, help_text='商品的库存数量', verbose_name='商品的库存数量')),
                ('market_price', models.FloatField(default=0, help_text='商品的市场价', verbose_name='商品的市场价')),
                ('shop_price', models.FloatField(default=0, help_text='现价', verbose_name='现价')),
                ('goods_brief', models.TextField(default='', help_text='商品的简介', verbose_name='商品的简介')),
                ('goods_desc', DjangoUeditor.models.UEditorField(blank=True, default='', help_text='商品描述', verbose_name='商品的描述')),
                ('ship_free', models.BooleanField(default=False, help_text='是否承担运费', verbose_name='是否承担运费')),
                ('goods_front_image', models.ImageField(blank=True, help_text='商品封面图', max_length=200, null=True, upload_to='Goods/%Y/%m', verbose_name='商品封面图')),
                ('is_new', models.BooleanField(default=False, help_text='是非新品', verbose_name='是非新品')),
                ('is_hot', models.BooleanField(default=False, help_text='是否热卖', verbose_name='是否热卖')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品管理',
                'verbose_name_plural': '商品管理',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='商品名称', max_length=30, verbose_name='商品名称')),
                ('code', models.CharField(blank=True, default='', help_text='英文名称', max_length=32, null=True, verbose_name='英文名称')),
                ('desc', models.TextField(default='', help_text='商品描述', verbose_name='简单描述')),
                ('category_type', models.IntegerField(choices=[(1, '一级类别'), (2, '二级类别'), (3, '三级类别')], help_text='商品类别', verbose_name='商品类别')),
                ('is_tab', models.BooleanField(default=False, help_text='是否显示导航', verbose_name='是否显示导航')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父类别', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.GoodsCategory', verbose_name='父类别')),
            ],
            options={
                'verbose_name': '商品类别管理',
                'verbose_name_plural': '商品类别管理',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='商品品牌名称', max_length=50, verbose_name='商品品牌名称')),
                ('desc', models.TextField(default='', help_text='商品的品牌描述', max_length=100, verbose_name='商品品牌描述')),
                ('image', models.ImageField(blank=True, help_text='品牌图片', max_length=200, null=True, upload_to='GoodsCategoryBrand/%Y/%m', verbose_name='品牌图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品品牌管理',
                'verbose_name_plural': '商品品牌管理',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='轮播图图片', max_length=200, null=True, upload_to='GoodsImage/%Y/%m', verbose_name='轮播图图片')),
                ('image_url', models.URLField(default='', help_text='图片地址', max_length=100, verbose_name='图片地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='上传时间', verbose_name='上传时间')),
                ('goods', models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品轮播图',
                'verbose_name_plural': '商品轮播图',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(help_text='商品的类别', on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类别'),
        ),
        migrations.AddField(
            model_name='banner',
            name='goods',
            field=models.ForeignKey(help_text='商品名称', on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品名称'),
        ),
    ]
