# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-14 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_goodscategorybrand_goodscate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodscategorybrand',
            old_name='goodscate',
            new_name='category',
        ),
        migrations.AlterModelTable(
            name='goodscategorybrand',
            table='goods_goodsbrand',
        ),
    ]
