# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-14 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20180414_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brandss', to='goods.GoodsCategory', verbose_name='商品类别'),
        ),
    ]
